### ISSUE TITLE
官方给个防沉迷demo吧，那个文档我看过了，对于小白来说有点难懂，调用sdk初始化没有反应，谢谢啦

### ISSUE THREAD

**Issue by xzfnn** [taptap/TapSDK-Android#16]

**Comment by hexinghuaxd** [comment]
https://zhuanlan.zhihu.com/p/446291058

**Comment by xzfnn** [comment]
> https://zhuanlan.zhihu.com/p/446291058

请问一下这个AntiAddictionUIKit.init方法初始化都没走进去一般是什么原因

**Comment by hexinghuaxd** [comment]
有报错日志吗？

**Comment by group900-3** [comment]
我这里也是，就闪了一下，回调注册了但是没执行，也没有报错。  
不过我打的debug包是正常的，打正式包就不弹窗

**Comment by hexinghuaxd** [comment]
group900-3 感谢提示，后续会增加混淆的配置
