### ISSUE TITLE
无法关闭TapTap快速认证

### ISSUE THREAD

**Issue by jin404861445lan** [taptap/TapSDK-Android#28]
enableTapLogin(false)没有生效是什么原因呢，老版本没问题。

**Comment by WatchMan-Wang** [comment]
您好，您遇到的这个现象是自 v3.18.2 版本开始更改的逻辑，属于预期之内的。enableTapLogin 更是一种登录方式的选择，如果应用中是选择的 TapTap 登录，这个参数可以设置成 true，其他的第三方登录方式可以设置成 false。
