### ISSUE TITLE
message:signature not match

### ISSUE THREAD

**Issue by newNcy** [TapTap/TapSDK-Android#3]
跟着taptap接入文档操作，登录时异常 message:signature not match

sdk 版本
![image](https://user-images.githubusercontent.com/19602632/120809624-db40b680-c57c-11eb-974c-f11e56dcd673.png)

gradle配置
![image](https://user-images.githubusercontent.com/19602632/120809701-edbaf000-c57c-11eb-8675-705435ae9ea0.png)

gradle build tool 版本 4.1.1
gradle 版本6.5

接入
![image](https://user-images.githubusercontent.com/19602632/120809936-29ee5080-c57d-11eb-9fc9-34a03140e4f3.png)

**Comment by newNcy** [comment]
初始化有错误信息，不知道有没有帮助
![image](https://user-images.githubusercontent.com/19602632/120810301-7c2f7180-c57d-11eb-82c9-db651a56243d.png)

**Comment by WatchMan-Wang** [comment]
TapTap使用客户端登陆会校验MD5签名, 异常提示签名有问题,  检查下Tap开发者后台填写的MD5, 注意不要有冒号; 看下签名证书是否配置错误;

**Comment by newNcy** [comment]
是签名的问题 谢谢大佬
